detectors:

  IrresponsibleModule:
    exclude:
      - Analyzer
      - FileStorage
      - Printer

  TooManyStatements:
    exclude:
      - main

  UtilityFunction:
    exclude:
      - custom_sort
