name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.1

      - run: bundle install

      - name: Reek
        run: reek

      - name: Rubocop
        run: rubocop

      - name: Rspec
        run: rspec
